services:
  - type: web
    name: pechaTool_Dashboard
    env: node
    plan: starter
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/OpenPecha/pecha-tools-landing-page
    branch: main
    buildCommand: npm ci --production=false && npm run build && npm prune --production
    startCommand: npx prisma migrate deploy && npm start
    envVars:
      - key: NODE_VERSION
        value: ~18.18.0
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: Dashboard-pg
          property: connectionString

databases:
  - name: Dashboard-pg
    plan: starter
